# Server & Port Configuration (Optional for now as you're using CLI)
server:
  host: "0.0.0.0"
  port: 8080

# Model Identity and Hardware
model:
  completion:
    engine: "openai" # change to vllm or openai to swap

    vllm:
      model_id: "Qwen/Qwen2.5-Coder-1.5B"
      gpu_memory_utilization: 0.7
      dtype: "half"

    openai:
      model_id: "gpt-5.1-codex-mini"
      api_key: "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"

# Global Inference Defaults (CompletionOptions)
# These apply to BOTH engines via your CompletionOptions class
inference:
  max_decoding_tokens: 128
  sampling_temperature: 0.2
  presence_penalty: 0.1
  seed: 42